# [START appengine_websockets_yaml]
runtime: nodejs16
env: flex

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
manual_scaling:
  instances: 1

network:
  session_affinity: true

env_variables:
  VAPID_PUBLIC: $VAPID_PUBLIC
  VAPID_SECRET: $VAPID_SECRET
  GCM_API_KEY: $GCM_API_KEY
  DATABASE_URL: $DATABASE_URL
  GCS_BUCKET: $GCS_BUCKET
  SERVER_URL: $SERVER_URL

# [END appengine_websockets_yaml]
