version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '12m'
    max-file: '5'
  driver: json-file

services:
  chat:
    image: quack:latest
    logging: *default-logging
    networks:
    - chat
    - webgateway
    environment:
    - COMMIT=${COMMIT_HASH}
    - NODE_ENV=production
    volumes:
    - ../env:/usr/src/app/.envrc
    - ../chat.config.js:/usr/src/app/chat.config.js
    - ../codecat-quack.json:/usr/src/app/secret.json
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.chat.tls: "true"
        traefik.http.routers.chat.tls.certresolver: cc
        traefik.http.routers.chat.tls.domains[0].main: chat.codecat.io
        traefik.http.routers.chat.tls.domains[0].sans: www.chat.codecat.io
        traefik.http.routers.chat.rule: Host(`chat.codecat.io`, `(sub:.*).chat.codecat.io`)
        traefik.http.routers.chat.priority: 30
        traefik.http.routers.chat.entrypoints: https
        traefik.http.routers.chat.middlewares: unwww@file
        traefik.http.routers.chat.service: chat
        traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: https
        traefik.http.services.chat.loadbalancer.server.port: 8080
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  chat:
    driver: overlay
  webgateway:
    external: true
