version: '3.6'

services:
  db:
    container_name: chat-db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
    ports:
      - 5433:5432
    volumes:
      - chat-db:/var/lib/postgresql/data

volumes:
  chat-db:
