version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: chat
      MONGO_INITDB_ROOT_PASSWORD: chat
    volumes:
      - chat-mongo:/data/db

volumes:
  chat-db:
  chat-mongo:
