
name: Native apps

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-android-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: sudo apt install libssl-dev

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: aarch64-linux-android

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'

    - uses: denoland/setup-deno@v2
      with:
        deno-version: '2.x'

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26d
        add-to-path: false

    - run: deno install --allow-scripts

    - run: npm i

    - name: setup Android signing
      run: |
        cd app/src-tauri/gen/android
        echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
        echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
        base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
        echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

    - run: deno task android:build
      env:
        NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        AR: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar
        RANLIB: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ranlib

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: |
          app/src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release.apk
