name: Build

on: workflow_dispatch

jobs:
  build:
    name: Build mobile app
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'pnpm'

    - name: apply secrets
      run: echo $CONFIG_FILE >> chat.config.js
      shell: bash
      env:
        CONFIG_FILE: ${{secrets.PRODUCTION_CONFIG}}

    - run: pnpm i

    - run: pnpm run build
      env: 
        NODE_ENV: production

    - run: pnpm exec cap sync
      working-directory: ./packages/app

    - name: Build with Gradle
      working-directory: ./packages/app/android
      run: ./gradlew build --warning-mode=all --stacktrace

    - name: Assemble Release Bundle
      working-directory: ./packages/app/android
      run: ./gradlew bundleRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDirectory: ./packages/app/android/app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
          
    - name: Create service_account.json
      run: echo '${{ secrets.GOOGLE_DEPLOY_KEY }}' > service_account.json

    - name: Deploy to Internal
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJson: service_account.json
        packageName: io.codecat.chat
        releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
        track: internal
        status: draft
