name: Quack CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: chat
          MONGO_INITDB_ROOT_PASSWORD: chat
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint:ci
    - run: npm run test:ci
      env:
        DATABASE_URL: mongodb://chat:chat@localhost:27017/chat?authSource=admin
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm i --production=false
    - run: npm run build
      env: 
        SERVER_URL: ${{ secrets.SERVER_URL }}
        NODE_ENV: production
    - run: npx cap sync
      working-directory: ./packages/app
    - name: Build with Gradle
      working-directory: ./packages/app/android
      run: ./gradlew build --warning-mode=all --stacktrace
    - name: Assemble Release Bundle
      working-directory: ./packages/app/android
      run: ./gradlew bundleRelease
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-bundle
        path: app/build/outputs/bundle/release
