name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SSH_HOST }}

    - name: Push changes to remote
      run: |
        git remote add prod ssh://raay@codecat.io:/var/docker/chat/app
        git push --verbose prod master:master -f
