name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy to codecat.io
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tag Release
      run: |
        version_name="$(cat package.json | awk '/version/{print $2}' | sed 's/[",]//g')"
        echo "Tagging release with tag $version_name"
        git push origin :refs/tags/$version_name
        git tag -f $version_name
        git push origin --tags

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: push changes to remote
      run: |
        git remote add prod raay@codecat.io:/var/docker/chat/app
        git push prod master:master -f

