name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Tag Release
      run: |
        version_name="v$(cat package.json | awk '/version/{print $2}' | sed 's/[",]//g')"
        echo "Tagging release with tag $version_name"
        git push origin :refs/tags/$version_name
        git tag -f $version_name
        git push origin --tags

    - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-host: ${{ secrets.SSH_HOST }}

    - name: apply secrets
      run: |
        echo $PRIVATE_KEY >> ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        echo $PUBLIC_KEY >> ~/.ssh/id_rsa.pub
      shell: bash
      env:
        PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        PUBLIC_KEY: ${{secrets.SSH_PUBLIC_KEY}}

    - name: test
      run: |
        ls ~/.ssh

    - name: Push changes to remote
      run: |
        git remote add prod ssh://raay@codecat.io:/var/docker/chat/app
        git push prod master:master -f --verbose
      env:
        GIT_SSH_COMMAND: ssh -i ~/.ssh/id_rsa
