name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    services:
      mongo:
        image: mongo:5
        env:
          MONGO_INITDB_ROOT_USERNAME: chat
          MONGO_INITDB_ROOT_PASSWORD: chat
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    env:
      NODE_ENV: 'test'
      DATABASE_URL: 'mongodb://chat:chat@localhost:27017/tests?authSource=admin'
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'pnpm'
    - run: pnpm i -g pnpm
    - run: pnpm i
    - run: pnpm run lint:ci
    - run: pnpm exec migrate-mongo up
    - run: pnpm run test:ci

  release-please:
    needs: 
    - tests
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{steps.release.outputs.release_created}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          token: ${{secrets.GITHUB_TOKEN}}
          command: manifest
