name: CI/CD

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5
        env:
          MONGO_INITDB_ROOT_USERNAME: chat
          MONGO_INITDB_ROOT_PASSWORD: chat
        options: >-
          --health-cmd mongo
          --health-interval 20s
          --health-timeout 10s
          --health-retries 5
        ports:
          - 27017:27017
    env:
      NODE_ENV: 'test'
      DATABASE_URL: 'mongodb://chat:chat@localhost:27017/tests?authSource=admin'
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - uses: denoland/setup-deno@v2
      with:
        deno-version: '2.x'
    - run: npm i
    - run: deno install --allow-scripts
    - run: deno task migrate:tests
    - run: deno task check

  release-please:
    needs: 
    - tests
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{steps.release.outputs.release_created}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          token: ${{secrets.GITHUB_TOKEN}}
          command: manifest
