name: Quack CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: chat
          MONGO_INITDB_ROOT_PASSWORD: chat
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint:ci
    - run: npm run test:ci
      env:
        DATABASE_URL: mongodb://chat:chat@localhost:27017/chat
