name: Quack CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: chat
          POSTGRES_PASSWORD: chat
          POSTGRES_DB: chat
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.x
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        cache: 'npm'
    - run: npm ci
    - run: npx knex migrate:latest
      env:
        DATABASE_URL: postgres://chat:chat@localhost:5432/chat
    - run: npm run lint:ci
    - run: npm run test:ci
      env:
        DATABASE_URL: postgres://chat:chat@localhost:5432/chat
